# Generated by Django 4.2 on 2023-04-12 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accueil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('carousel_image', models.ImageField(upload_to='home/images')),
            ],
        ),
        migrations.CreateModel(
            name='Aproposde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('banner_image', models.ImageField(upload_to='about/banner')),
                ('certificat', models.ImageField(upload_to='about/certificat')),
            ],
        ),
        migrations.CreateModel(
            name='equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_image', models.ImageField(upload_to='about/team')),
                ('nom', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=150)),
                ('linkedin', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TopBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('adresse', models.CharField(max_length=200)),
                ('phone_number', models.CharField(max_length=200)),
                ('linkedin', models.CharField(max_length=255)),
                ('instagram', models.CharField(max_length=255)),
                ('facebook', models.CharField(max_length=255)),
                ('twitter', models.CharField(max_length=255)),
                ('youtube', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Home',
        ),
    ]
