# Generated by Django 4.2 on 2023-04-12 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0002_accueil_aproposde_equipe_topbar_delete_home'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accueil',
            options={'verbose_name_plural': 'Accueil'},
        ),
    ]
