# Generated by Django 4.2 on 2023-04-12 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0003_alter_accueil_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aproposde',
            options={'verbose_name_plural': 'Qui Somme nous'},
        ),
        migrations.AlterModelOptions(
            name='equipe',
            options={'verbose_name_plural': 'equipe'},
        ),
        migrations.AlterModelOptions(
            name='topbar',
            options={'verbose_name_plural': 'Top bar'},
        ),
    ]
