# Generated by Django 4.2 on 2023-04-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0004_alter_aproposde_options_alter_equipe_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='certificat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.TextField(max_length=150)),
                ('certificat', models.ImageField(upload_to='about/certificat')),
            ],
            options={
                'verbose_name_plural': 'certificat',
            },
        ),
        migrations.RemoveField(
            model_name='aproposde',
            name='certificat',
        ),
    ]
