# Generated by Django 4.2 on 2023-04-12 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0005_certificat_remove_aproposde_certificat'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Aproposde',
            new_name='Qui_Somme_Nous',
        ),
    ]
