# Generated by Django 4.2 on 2023-04-12 17:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0006_rename_aproposde_qui_somme_nous'),
    ]

    operations = [
        migrations.AddField(
            model_name='topbar',
            name='email',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
    ]
