# Generated by Django 4.2 on 2023-04-13 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0008_certificat_accueil'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueil',
            name='nombre_de_certificat',
            field=models.IntegerField(default=0),
        ),
    ]
