# Generated by Django 4.2 on 2023-04-13 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0009_accueil_nombre_de_certificat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accueil',
            options={'verbose_name_plural': 'Accueil_Slider'},
        ),
        migrations.RemoveField(
            model_name='accueil',
            name='nombre_de_certificat',
        ),
        migrations.RemoveField(
            model_name='certificat',
            name='accueil',
        ),
    ]
