# Generated by Django 4.2 on 2023-04-13 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0011_visitorcount'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='TopBar',
            new_name='informations',
        ),
        migrations.AlterModelOptions(
            name='informations',
            options={'verbose_name_plural': 'informations'},
        ),
    ]
