# Generated by Django 4.2 on 2023-04-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0012_rename_topbar_informations_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccueilInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_de_project', models.IntegerField(max_length=255)),
                ('nombre_certificat', models.IntegerField(max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Accueil_informations',
            },
        ),
    ]
