# Generated by Django 4.2 on 2023-04-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0013_accueilinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='accueilinfo',
            name='titre',
            field=models.TextField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='accueilinfo',
            name='nombre_certificat',
            field=models.IntegerField(blank=True, max_length=255, null=True),
        ),
    ]
