# Generated by Django 4.2 on 2023-04-14 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0014_accueilinfo_titre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_image', models.ImageField(upload_to='blog/images')),
                ('titre', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'acctualite',
            },
        ),
        migrations.AlterField(
            model_name='certificat',
            name='titre',
            field=models.CharField(max_length=100),
        ),
    ]
