# Generated by Django 4.2 on 2023-04-14 03:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0017_contact_alter_accueilinfo_nombre_certificat_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='response',
            field=models.TextField(blank=True, null=True),
        ),
    ]
