# Generated by Django 4.2 on 2023-04-14 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0018_contact_response'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='response',
            new_name='reponse',
        ),
    ]
