# Generated by Django 4.2 on 2023-04-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agrilabo_app', '0020_remove_accueilinfo_nombre_certificat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accueilinfo',
            name='nombre_de_certificat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accueilinfo',
            name='nombre_de_project',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
